Repository BoardSignal/Team-CivilWar-BoardSignal-FE, pull requests merged in 2024-03, with the labels that each got.

#71 [#68]Feat: 보드게임 공략 작성 페이지
  src/apis/kakaoLogin.ts
  src/apis/naverLogin.ts
  src/apis/postBoardGameTip.ts
  src/pages/CreateBoardGameTip/hooks/useCreateBoardGameTip.ts
  src/pages/CreateBoardGameTip/index.tsx
  src/pages/Login/hooks/useKakaoLogin.ts
  src/pages/Login/hooks/useNaverLogin.ts
  src/stories/pages/CreateTip/index.stories.tsx
Labels: ✨ Feature

#70 [#35] Feat: 공통컴포넌트 - OptionFilterBar
  .storybook/preview.tsx
  src/assets/icon-sprite.svg
  src/components/Drawer/DrawerClose.tsx
  src/components/Drawer/DrawerContent.tsx
  src/components/Drawer/DrawerTitle.tsx
  src/components/Drawer/DrawerTrigger.tsx
  src/components/Drawer/index.tsx
  src/components/Icon/type.ts
  src/components/MultipleSelect/index.tsx
  src/components/OptionFilterBar/OptionDrawer.tsx
  src/components/OptionFilterBar/OptionFilterButton.tsx
  src/components/OptionFilterBar/index.tsx
  src/index.css
  src/stories/components/Drawer.stories.tsx
  src/stories/components/OptionFilterBar.stories.tsx
Labels: ✨ Feature

#75 [#41] Feat: 공통컴포넌트 - Select
  src/components/Select/index.tsx
  src/stories/components/Select.stories.tsx
Labels: ✨ Feature

#80 [#79] Feat: 로딩, 오류, Api mocking 처리 방법 추가
  .github/workflows/publish-storybook.yaml
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  src/ReactQueryClientProvider.tsx
  src/Router.tsx
  src/apis/core.ts
  src/apis/core/authentication.ts
  src/apis/core/constants.ts
  src/apis/core/index.ts
  src/apis/core/makeMutationResponse.ts
  src/apis/core/makeQueryResponse.ts
  src/apis/kakaoLogin.ts
  src/apis/naverLogin.ts
  src/apis/notifications.ts
  src/assets/icon-sprite.svg
  src/assets/notification-thumbnail-review.png
  src/components/Button/index.tsx
  src/components/ErrorAlertFullScreen/index.tsx
  src/components/ErrorBoundary/ApiErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/GNB/index.tsx
  src/components/Icon/type.ts
  src/components/Layout/Introduction.tsx
  src/components/Layout/RootLayout.tsx
  src/components/Layout/ToastRoot.tsx
  src/components/Layout/index.tsx
  src/components/Ripple/index.tsx
  src/components/Spinner/SpinnerFullScreen.tsx
  src/components/Spinner/index.tsx
  src/components/TabBar/index.tsx
  src/main.tsx
  src/mocks/index.tsx
  src/mocks/notifications.tsx
  src/pages/NotificationList/components/NotificationList/NotificationListItem.tsx
  src/pages/NotificationList/components/NotificationList/index.tsx
  src/pages/NotificationList/index.tsx
  src/stories/CommonPageLayoutDecorator.tsx
  src/stories/components/ErrorAlertFullScreen.stories.tsx
  src/stories/components/Spinner.stories.tsx
  src/stories/components/SpinnerFullScreen.stories.tsx
  src/stories/examples/errors/MutationBadRequest.stories.tsx
  src/stories/examples/errors/MutationError.stories.tsx
  src/stories/examples/errors/QueryError.stories.tsx
  src/stories/pages/NotificationList/index.stories.tsx
  src/utils/showToast.tsx
  src/utils/useErrorBoundary.ts
Labels: ✨ Feature

#72 [#69] Feat: 공통컴포넌트 - UserProfile
  src/components/UserProfile/UserSignalTemperature.tsx
  src/components/UserProfile/index.tsx
  src/pages/Profile/components/SignalTemperature/index.tsx
  src/stories/components/UserProfile.stories.tsx
  src/utils/getColorByTemperature.ts
Labels: ✨ Feature

#85 [#66] Feat: 공통컴포넌트 - GatheringList
  src/assets/default-thumbnail-image.png
  src/components/GatheringList/GatheringItem.tsx
  src/components/GatheringList/index.tsx
  src/stories/components/GatheringList.stories.tsx
  src/utils/time.ts
Labels: ✨ Feature

#78 [#62] Feat: 보드게임 상세페이지
  src/Router.tsx
  src/apis/boardGameDetail.ts
  src/apis/boardGameTip.ts
  src/apis/boardGameTipLike.ts
  src/apis/boardGameWish.ts
  src/assets/icon-sprite.svg
  src/components/Chip/index.tsx
  src/components/Icon/type.ts
  src/mocks/boardGameDetail.tsx
  src/mocks/index.tsx
  src/pages/BoardGameDetail/components/BoardGameTipList/MyTipItem.tsx
  src/pages/BoardGameDetail/components/BoardGameTipList/TipItem.tsx
  src/pages/BoardGameDetail/components/BoardGameTipList/index.tsx
  src/pages/BoardGameDetail/components/GameSummary/index.tsx
  src/pages/BoardGameDetail/components/GameWish/index.tsx
  src/pages/BoardGameDetail/hooks/useBoardGameTipLike.ts
  src/pages/BoardGameDetail/hooks/useBoardGameWish.ts
  src/pages/BoardGameDetail/index.tsx
  src/pages/CreateBoardGameTip/hooks/useCreateBoardGameTip.ts
  src/pages/MyProfile/components/PersonalInfo/index.tsx
  src/pages/MyProfile/components/SignalTemperature/index.tsx
  src/pages/Profile/components/MannerReview/index.tsx
  src/pages/Profile/components/PersonalInfo/index.tsx
  src/pages/Profile/components/PreferCategory/index.tsx
  src/pages/Profile/components/SignalTemperature/index.tsx
  src/pages/Profile/index.tsx
  src/stories/pages/BoardGameDetail/BoardGameTipList.stories.tsx
  src/stories/pages/BoardGameDetail/GameWish.stories.tsx
  src/stories/pages/BoardGameDetail/index.stories.tsx
  src/stories/pages/MyProfile/PersonalInfo.stories.tsx
  src/stories/pages/MyProfile/Temperature.stories.tsx
  src/stories/pages/Profile/PersonalInfo.stories.tsx
  src/stories/pages/Profile/Review.stories.tsx
  src/stories/pages/Profile/Temperature.stories.tsx
  src/stories/pages/Profile/index.stories.tsx
Labels: ✨ Feature

#97 [#95] Feat: BadRequest Response Body에 code 필드 추가하기
  src/apis/core/makeMutationResponse.ts
Labels: ✨ Feature

#104 [#103] Feat: 페이지 컴포넌트들을 위한 전역 Suspense 추가
  src/components/Layout/index.tsx
  src/stories/CommonPageLayoutDecorator.tsx
Labels: ✨ Feature

#86 [#81]Feat: 프로필 페이지 더미데이터 제거 및 실제 데이터로 변경
  src/Router.tsx
  src/apis/userProfile.ts
  src/pages/Profile/components/EditProfileButton/index.tsx
  src/pages/Profile/components/EndedGatheringButton/index.tsx
  src/pages/Profile/components/MannerReview/index.tsx
  src/pages/Profile/components/PersonalInfo/index.tsx
  src/pages/Profile/components/PreferCategory/index.tsx
  src/pages/Profile/components/SignalTemperature/index.tsx
  src/pages/Profile/components/WishGameButton/index.tsx
  src/pages/Profile/index.tsx
Labels: ✨ Feature

#106 [#102] Refactor: 메시지 상수화
  src/ReactQueryClientProvider.tsx
  src/components/ErrorAlertFullScreen/index.tsx
  src/components/Layout/Introduction.tsx
  src/components/UserProfile/UserSignalTemperature.tsx
  src/constants/messages/alert.ts
  src/constants/messages/boardSignal.ts
  src/constants/messages/error.ts
  src/constants/messages/modal.ts
  src/pages/Login/index.tsx
  src/pages/Profile/components/SignalTemperature/index.tsx
Labels: 🔨 Refactor

#89 [#84] Feat: 장소 피커 구현 (풀 스크린 모달, 카카오맵 API를 활용한)
  .github/workflows/publish-storybook.yaml
  src/apis/kakaoMapScript.ts
  src/apis/kakaoMapSearch.ts
  src/apis/types/KakaoMapSearch.d.ts
  src/components/Button/Ripple.tsx
  src/components/Button/RippleEffect.tsx
  src/components/Button/index.tsx
  src/components/ErrorAlertFullScreen/index.tsx
  src/components/GatheringList/GatheringListItem.tsx
  src/components/GatheringList/index.tsx
  src/components/InfiniteScrollAutoFetcher/FetchMarker.tsx
  src/components/InfiniteScrollAutoFetcher/index.tsx
  src/components/LocationSelect/LocationList.tsx
  src/components/LocationSelect/LocationListItem.tsx
  src/components/LocationSelect/LocationListModal.tsx
  src/components/LocationSelect/index.tsx
  src/components/Spinner/SpinnerListBottom.tsx
  src/components/TextInputWithIcon/index.tsx
  src/hooks/useAutoCloseModal.ts
  src/stories/components/LocationSelect.stories.tsx
Labels: ✨ Feature

#111 Refactor: #88의 폼 코드 분리 제안
  src/pages/GatheringCreate/components/GatheringCreateForm/formSchema.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/gatheringCreateRequestMapper.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/useCreateGathering.ts
Labels: 🔨 Refactor

#88 [#76] Feat: 모임 생성 페이지
  package.json
  pnpm-lock.yaml
  src/Router.tsx
  src/apis/getLoggedInUser.ts
  src/apis/postGatheringCreate.ts
  src/components/Checkbox/index.tsx
  src/components/ErrorAlertFullScreen/index.tsx
  src/components/FormErrorMessage/index.tsx
  src/components/ImageUpload/ImageUploadButton.tsx
  src/components/ImageUpload/index.tsx
  src/components/Modal/index.tsx
  src/components/Range/index.tsx
  src/components/Select/index.tsx
  src/components/TextArea/index.tsx
  src/components/TextInput/index.tsx
  src/components/alert/index.tsx
  src/constants/boardgameCategories.ts
  src/constants/times.ts
  src/index.css
  src/mocks/auth.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/formSchema.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/gatheringCreateRequestMapper.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/useCreateGathering.ts
  src/pages/GatheringCreate/index.tsx
  src/stories/components/Select.stories.tsx
  src/stories/pages/GatheringCreatePage.stories.tsx
Labels: ✨ Feature

#105 [#77] Feat: 로그인, 로그아웃, 리프레시 기능 구현
  src/Router.tsx
  src/apis/core/authentication.ts
  src/apis/core/constants.ts
  src/apis/core/index.ts
  src/apis/kakaoLogin.ts
  src/apis/logout.ts
  src/apis/naverLogin.ts
  src/constants/apiRoutes.ts
  src/constants/messages/error.ts
  src/mocks/auth.tsx
  src/mocks/boardGameDetail.tsx
  src/mocks/notifications.tsx
  src/pages/Login/components/LoginButtons.tsx
  src/pages/Login/hooks/useKakaoLogin.ts
  src/pages/Login/hooks/useNaverLogin.ts
  src/pages/Login/index.tsx
  src/pages/Profile/hooks/useLogout.ts
  src/pages/Profile/index.tsx
  src/pages/RedirectOnAuthentication/index.tsx
  src/stories/examples/errors/MutationBadRequest.stories.tsx
Labels: ✨ Feature

#125 [#124] Refactor: Chromatic 배포 환경의 baseUrl을 GitHub Action 환경 변수를 쓰도록 변경
  .github/workflows/publish-storybook.yaml
Labels: 🔨 Refactor

#121 [#120] Refactor: GNB, Router 파일에 상수 주소 반영
  src/Router.tsx
  src/components/GNB/index.tsx
  src/components/GNB/routes.ts
Labels: 🔨 Refactor

#109 [#108] Feat: 다크모드 컬러 팔레트 구성 및 color-scheme에 따라 자동 지정하기
  .storybook/main.ts
  .storybook/preview.tsx
  index.html
  package.json
  pnpm-lock.yaml
  src/components/Button/RippleEffect.tsx
  src/components/Drawer/index.tsx
  src/components/GNB/index.tsx
  src/components/Layout/RootLayout.tsx
  src/components/Modal/index.tsx
  src/components/Popover/index.tsx
  src/components/TabBar/index.tsx
  src/components/TextArea/index.tsx
  src/components/TextInput/index.tsx
  src/components/TextInputWithIcon/index.tsx
  src/components/UserProfile/UserSignalTemperature.tsx
  src/constants/storageKeys.ts
  src/index.css
  src/main.tsx
  src/mocks/index.tsx
  src/mocks/profiles.tsx
  src/pages/GatheringFix/index.tsx
  src/pages/Profile/components/EditProfileButton/index.tsx
  src/pages/Profile/components/EndedGatheringButton/index.tsx
  src/pages/Profile/components/MannerReview/index.tsx
  src/pages/Profile/components/PersonalInfo/index.tsx
  src/pages/Profile/components/PreferCategory/index.tsx
  src/pages/Profile/components/SignalTemperature/index.tsx
  src/pages/Profile/components/WishGameButton/index.tsx
  src/pages/Profile/index.tsx
  src/stories/CommonPageLayoutDecorator.tsx
  src/stories/components/Drawer.stories.tsx
  src/stories/pages/BoardGameDetail/GameWish.stories.tsx
  src/stories/pages/BoardGameDetail/index.stories.tsx
  src/stories/pages/Profile/MannerReview.stories.tsx
  src/stories/pages/Profile/PersonalInfo.stories.tsx
  src/stories/pages/Profile/SignalTemperature.stories.tsx
  src/stories/pages/Profile/index.stories.tsx
  src/utils/activateColorTheme.ts
  src/utils/showToast.tsx
  tailwind.config.js
Labels: ✨ Feature

#99 [#93] Feat: 모임 상세 페이지 - 참가자 목록
  src/components/UserProfile/index.tsx
  src/pages/GatheringDetail/GatheringParticipants/index.tsx
  src/stories/components/UserProfile.stories.tsx
  src/stories/pages/GatheringDetail/GatheringParticipants.stories.tsx
Labels: ✨ Feature

#92 [#63] Feat: 모임 상세 페이지 - 모임 소개
  src/pages/GatheringDetail/GatheringIntroduce/components/GatheringDescription/index.tsx
  src/pages/GatheringDetail/GatheringIntroduce/components/GatheringGuide/index.tsx
  src/pages/GatheringDetail/GatheringIntroduce/components/TabMenu/index.tsx
  src/pages/GatheringDetail/GatheringIntroduce/index.tsx
  src/stories/pages/GatheringDetail/GatheringDescription.stories.tsx
  src/stories/pages/GatheringDetail/GatheringGuide.stories.tsx
  src/stories/pages/GatheringDetail/GatheringIntroduce.stories.tsx
Labels: ✨ Feature

#123 [#118] Feat: 모임 확정 취소 사유 작성 페이지
  src/Router.tsx
  src/apis/boardGameDetail.ts
  src/apis/boardGameTip.ts
  src/apis/boardGameTipLike.ts
  src/apis/boardGameWish.ts
  src/apis/gatheringCreate.ts
  src/apis/gatheringDetail.ts
  src/apis/gatheringUnfix.ts
  src/apis/kakaoMapScript.ts
  src/apis/kakaoMapSearch.ts
  src/apis/loggedInUser.ts
  src/apis/notifications.ts
  src/apis/userProfile.ts
  src/constants/messages/placeholder.ts
  src/constants/queryKey.ts
  src/hooks/useGetLoggedInUserId.ts
  src/mocks/auth.tsx
  src/mocks/gatheringDetail.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/useCreateGathering.ts
  src/pages/GatheringCreate/index.tsx
  src/pages/GatheringUnfix/components/GatheringUnfixForm/formSchema.ts
  src/pages/GatheringUnfix/components/GatheringUnfixForm/index.tsx
  src/pages/GatheringUnfix/hooks/useGatheringUnfix.ts
  src/pages/GatheringUnfix/index.tsx
  src/stories/pages/GatheringUnfixPage.stories.tsx
Labels: ✨ Feature

#114 [#112] Feat: 보드게임 공략 작성 페이지 구현
  src/Router.tsx
  src/apis/boardGameTip.ts
  src/apis/core/authentication.ts
  src/components/Modal/index.tsx
  src/constants/storageKeys.ts
  src/pages/CreateBoardGameTip/components/CreateBoardGameTipForm/index.tsx
  src/pages/CreateBoardGameTip/components/CreateBoardGameTipForm/useCreateBoardGameTip.ts
  src/pages/CreateBoardGameTip/hooks/useCreateBoardGameTip.ts
  src/pages/CreateBoardGameTip/index.tsx
  src/pages/Profile/hooks/useLogout.ts
  src/pages/RedirectOnAuthentication/index.tsx
  src/stories/pages/CreateBoardGameTip/index.stories.tsx
  src/stories/pages/CreateTip/index.stories.tsx
Labels: ✨ Feature

#126 [#119] Feat: 보드게임 상세페이지 - 내 공략 삭제
  src/apis/boardGameTip.ts
  src/constants/messages/modal.ts
  src/pages/BoardGameDetail/components/BoardGameTipList/MyTipItem.tsx
  src/pages/BoardGameDetail/components/BoardGameTipList/index.tsx
  src/pages/BoardGameDetail/hooks/useDeleteBoardGameTip.ts
Labels: ✨ Feature

#129 [#128]Feat: 프로텍트 라우트 구현
  src/Router.tsx
  src/apis/getLoggedInUser.ts
  src/components/AuthorizedRoute/index.tsx
  src/constants/messages/error.ts
  src/hooks/useGetLoggedInUserId.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
Labels: ✨ Feature

#133 [#131]Feat: 프로필 수정 페이지
  src/Router.tsx
  src/apis/userProfileEdit.ts
  src/pages/ProfileEdit/components/ProfileEditForm/formSchema.ts
  src/pages/ProfileEdit/components/ProfileEditForm/index.tsx
  src/pages/ProfileEdit/components/ProfileEditForm/profileEditMapper.ts
  src/pages/ProfileEdit/components/ProfileEditForm/useProfileEdit.ts
  src/pages/ProfileEdit/index.tsx
  src/stories/pages/ProfileEditPage.stories.tsx
Labels: ✨ Feature

#130 [#10] Feat: 회원가입 페이지 구현
  src/Router.tsx
  src/components/Modal/index.tsx
  src/constants/messages/boardSignal.ts
  src/pages/Register/components/RegisterForm/Agreement.tsx
  src/pages/Register/components/RegisterForm/formSchema.ts
  src/pages/Register/components/RegisterForm/index.tsx
  src/pages/Register/components/RegisterForm/registerMapper.ts
  src/pages/Register/components/RegisterForm/useRegister.ts
  src/pages/Register/index.tsx
  src/stories/pages/SignUpPage.stories.tsx
Labels: ✨ Feature

#116 [#115] Feat: FCM 토큰값 조회
  package.json
  pnpm-lock.yaml
  public/firebase-messaging-sw.js
  src/apis/FCMToken.ts
  src/constants/apiRoutes.ts
  src/constants/storageKeys.ts
  src/hooks/useInitializeFCM.ts
  src/pages/HomePage.tsx
Labels: ✨ Feature

#135 [#107] Feat: 404 페이지 처리
  src/Router.tsx
  src/apis/boardGameDetail.ts
  src/apis/userProfile.ts
  src/components/ErrorAlertFullScreen/AlertProps.ts
  src/components/ErrorAlertFullScreen/DefaultErrorAlertFullScreen.tsx
  src/components/ErrorAlertFullScreen/NotFoundErrorAlertFullScreen/InvalidStatePageError.tsx
  src/components/ErrorAlertFullScreen/NotFoundErrorAlertFullScreen/checkIsGetNotFound.ts
  src/components/ErrorAlertFullScreen/NotFoundErrorAlertFullScreen/checkIsInvalidStatePage.ts
  src/components/ErrorAlertFullScreen/NotFoundErrorAlertFullScreen/index.tsx
  src/components/ErrorAlertFullScreen/NotFoundErrorAlertFullScreen/notFoundFallback.ts
  src/components/ErrorAlertFullScreen/UnknownErrorAlertFullScreen/index.tsx
  src/components/ErrorAlertFullScreen/index.tsx
  src/components/ErrorBoundary/ApiErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/constants/messages/error.ts
  src/pages/BoardGameDetail/components/GameWish/index.tsx
  src/pages/BoardGameDetail/index.tsx
  src/pages/Profile/index.tsx
  src/stories/components/DefaultErrorAlertFullScreen.stories.tsx
  src/stories/components/ErrorAlertFullScreen.stories.tsx
  src/stories/components/NotFoundFullScreen.stories.tsx
Labels: ✨ Feature

#141 [#140] Fix: Fcm토큰 조회
  src/apis/FCMToken.ts
  src/hooks/useInitializeFCM.ts
Labels: 🐞 Fix

#134 [#9] Feat: 모임 목록 페이지
  package.json
  pnpm-lock.yaml
  src/Router.tsx
  src/apis/gatheringCreate.ts
  src/apis/getGatheringList.ts
  src/assets/icon-sprite.svg
  src/assets/tab-bar-logo.png
  src/components/Drawer/DrawerContent.tsx
  src/components/GatheringList/GatheringListItem.tsx
  src/components/GatheringList/index.tsx
  src/components/GatheringListItem/index.tsx
  src/components/MultipleSelect/index.tsx
  src/components/OptionFilterBar/OptionDrawer.tsx
  src/components/OptionFilterBar/OptionFilterButton.tsx
  src/components/OptionFilterBar/index.tsx
  src/constants/messages/alert.ts
  src/constants/options.ts
  src/constants/times.ts
  src/mocks/gatheringList.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/formSchema.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/gatheringCreateRequestMapper.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/useCreateGathering.ts
  src/pages/GatheringList/components/FloatingButton/index.tsx
  src/pages/GatheringList/components/GatheringList/index.tsx
  src/pages/GatheringList/index.tsx
  src/pages/ProfileEdit/components/ProfileEditForm/index.tsx
  src/pages/Register/components/RegisterForm/index.tsx
  src/stories/components/GatheringList.stories.tsx
  src/stories/components/GatheringListItem.stories.tsx
  src/stories/components/OptionFilterBar.stories.tsx
  src/stories/pages/GatheringListPage.stories.tsx
Labels: ✨ Feature

#137 [#132] Feat: 모임확정 페이지 - DatePicker 구현 및 페이지 구현
  package.json
  pnpm-lock.yaml
  src/Router.tsx
  src/apis/postGatheringFix.ts
  src/assets/icon-sprite.svg
  src/components/DatePicker/Calendar.tsx
  src/components/DatePicker/buttonVariants.ts
  src/components/DatePicker/index.tsx
  src/components/Icon/type.ts
  src/components/LocationSelect/LocationListModal.tsx
  src/components/Select/index.tsx
  src/components/SubwaySelect/SubwayListModal.tsx
  src/pages/GatheringFix/GatheringFixForm/formSchema.ts
  src/pages/GatheringFix/GatheringFixForm/gatheringFixRequestMapper.ts
  src/pages/GatheringFix/GatheringFixForm/index.tsx
  src/pages/GatheringFix/GatheringFixForm/useGatheringFix.ts
  src/pages/GatheringFix/index.tsx
  src/stories/components/DatePicker.stories.tsx
  src/utils/extractFromSubwayName.ts
Labels: ✨ Feature

#143 [#142] Fix: 프로필 라우팅처리 수정 및 시그널온도 Undefined 출력 수정
  src/Router.tsx
  src/apis/userProfile.ts
  src/pages/Profile/components/EditProfileButton/index.tsx
  src/pages/Profile/index.tsx
Labels: 🐞 Fix

#145 [#144] Fix: 페이지 트랜지션 버그 수정
  src/Router.tsx
Labels: 🐞 Fix

#149 [#148] Fix: useAutoCloseOnGoBack의 동작 불능 수정
  src/hooks/useAutoCloseModal.ts
Labels: 🐞 Fix

#150 [#47] Feat: 알림 목록 조회 페이지와 빈 목록 페이지
  src/apis/notifications.ts
  src/assets/icon-sprite.svg
  src/components/EmptyListFullScreen/EmptyListSmall.tsx
  src/components/EmptyListFullScreen/index.tsx
  src/components/Icon/type.ts
  src/constants/apiRoutes.ts
  src/constants/messages/emptyScreens.ts
  src/constants/pageRoutes.ts
  src/main.tsx
  src/mocks/notifications.tsx
  src/pages/NotificationList/components/NotificationList/NotificationListItem.tsx
  src/pages/NotificationList/components/NotificationList/index.tsx
  src/stories/components/EmptyListFullScreen.stories.tsx
  src/stories/components/EmptyListSmall.stories.tsx
  src/stories/pages/NotificationList/index.stories.tsx
Labels: ✨ Feature

#151 [#138] Feat: 보드게임 목록 페이지
  src/Router.tsx
  src/apis/boardGameList.ts
  src/apis/notifications.ts
  src/components/OptionFilterBar/index.tsx
  src/constants/messages/emptyScreens.ts
  src/constants/options.ts
  src/constants/queryKey.ts
  src/mocks/boardGameList.tsx
  src/pages/BoardGameList/components/BoardGameList/BoardGameListItem.tsx
  src/pages/BoardGameList/components/BoardGameList/index.tsx
  src/pages/BoardGameList/components/BoardGameListOptionFilterBar/index.tsx
  src/pages/BoardGameList/hooks/useBoardGameListQueryParams/index.tsx
  src/pages/BoardGameList/index.tsx
  src/stories/pages/BoardGameListPage.stories.tsx
Labels: ✨ Feature

#147 [#139]Feat: 모임 상세 페이지 구현
  src/Router.tsx
  src/apis/gatheringDelete.ts
  src/apis/gatheringDetail.ts
  src/apis/gatheringEntrance.ts
  src/apis/gatheringLeave.ts
  src/apis/kickParticipant.ts
  src/components/UserProfile/index.tsx
  src/constants/messages/modal.ts
  src/mocks/gatheringDetail.ts
  src/pages/GatheringDetail/GatheringIntroduce/index.tsx
  src/pages/GatheringDetail/GatheringParticipants/index.tsx
  src/pages/GatheringDetail/components/GatheringButton/index.tsx
  src/pages/GatheringDetail/components/GatheringDescription/index.tsx
  src/pages/GatheringDetail/components/GatheringGuide/index.tsx
  src/pages/GatheringDetail/components/GatheringIntroduce/index.tsx
  src/pages/GatheringDetail/components/GatheringParticipants/index.tsx
  src/pages/GatheringDetail/components/TabMenu/index.tsx
  src/pages/GatheringDetail/hooks/useGatheringDelete.ts
  src/pages/GatheringDetail/hooks/useGatheringEntrance.ts
  src/pages/GatheringDetail/hooks/useGatheringLeave.ts
  src/pages/GatheringDetail/hooks/useKickParticipant.ts
  src/pages/GatheringDetail/index.tsx
  src/pages/GatheringFix/index.tsx
  src/stories/components/UserProfile.stories.tsx
  src/stories/pages/GatheringDetail/GatheringDescription.stories.tsx
  src/stories/pages/GatheringDetail/GatheringGuide.stories.tsx
  src/stories/pages/GatheringDetail/GatheringIntroduce.stories.tsx
  src/stories/pages/GatheringDetail/GatheringParticipants.stories.tsx
  src/stories/pages/GatheringDetail/index.stories.tsx
Labels: ✨ Feature

#154 [#152] Feat: 채팅 목록 페이지, 채팅방 페이지 구현
  index.html
  package.json
  pnpm-lock.yaml
  src/Router.tsx
  src/apis/chatRoomList.ts
  src/apis/chatRoomMessages.ts
  src/apis/gatheringDetail.ts
  src/assets/default-profile-image.png
  src/components/GatheringListItem/index.tsx
  src/components/ReverseInfiniteScrollAutoFetch/index.tsx
  src/constants/apiRoutes.ts
  src/constants/queryKey.ts
  src/hooks/useChatting.ts
  src/hooks/useIntersectionObserver.ts
  src/mocks/chatRoom.ts
  src/mocks/gatheringDetail.ts
  src/pages/ChatRoom/components/ChatBubble/index.tsx
  src/pages/ChatRoom/components/ChatContainer/index.tsx
  src/pages/ChatRoom/components/ChatInput/index.tsx
  src/pages/ChatRoom/index.tsx
  src/pages/ChatRoomList/components/ChatRoomList/ChatRoomListItem.tsx
  src/pages/ChatRoomList/components/ChatRoomList/index.tsx
  src/pages/ChatRoomList/index.tsx
  src/pages/GatheringDetail/index.tsx
  src/pages/GatheringUnfix/index.tsx
  src/stories/pages/ChatRoom/ChatBubble.stories.tsx
  src/stories/pages/ChatRoom/index.stories.tsx
  src/utils/time.ts
Labels: ✨ Feature

#155 [#117] Feat: 진행한 게임 목록 조회 페이지 구현
  src/Router.tsx
  src/apis/endGameList.ts
  src/apis/gatheringList.ts
  src/apis/getLoggedInUser.ts
  src/apis/loggedInUser.ts
  src/components/AuthorizedRoute/index.tsx
  src/components/GatheringListItem/index.tsx
  src/constants/boardSignal.ts
  src/constants/queryKey.ts
  src/hooks/useGetLoggedInUserId.ts
  src/mocks/endgames.ts
  src/pages/EndGames/components/EndGameList/index.tsx
  src/pages/EndGames/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringDetail/index.tsx
  src/pages/GatheringList/components/GatheringList/index.tsx
  src/pages/Profile/index.tsx
  src/stories/pages/EndGamesPage.stories.tsx
  src/utils/time.ts
Labels: ✨ Feature

#153 [#100] Feat: 리뷰 등록 페이지
  src/Router.tsx
  src/apis/endGameUser.ts
  src/apis/gatheringDetail.ts
  src/apis/reviewCreate.ts
  src/components/GatheringList/GatheringListItem.tsx
  src/components/GatheringList/index.tsx
  src/components/UserProfile/index.tsx
  src/constants/apiRoutes.ts
  src/constants/queryKey.ts
  src/pages/ReviewCreate/components/ReviewForm/index.tsx
  src/pages/ReviewCreate/components/ReviewSelect/index.tsx
  src/pages/ReviewCreate/index.tsx
  src/stories/components/UserProfile.stories.tsx
  src/stories/pages/ReviewCreate/ReviewForm.stories.tsx
  src/stories/pages/ReviewCreate/ReviewSelect.stories.tsx
  src/stories/pages/ReviewCreate/index.stories.tsx
Labels: ✨ Feature

#157 [#156] Fix: 환경 변수 변경
  .github/workflows/publish-storybook.yaml
  src/constants/apiRoutes.ts
  src/hooks/useChatting.ts
  src/pages/Login/components/LoginButtons.tsx
Labels: 🐞 Fix

#159 [#158] Fix: 누락된 페이지, AuthorizedRoute 추가
  src/Router.tsx
Labels: 🐞 Fix

#161 [#160] Fix: Router 버그 수정
  src/Router.tsx
Labels: 🐞 Fix

#163 [#162]Fix: 페이지 인증 라우터 추가 및 FCM 토큰 조회코드 위치 변경
  src/Router.tsx
  src/pages/GatheringList/index.tsx
  src/pages/HomePage.tsx
Labels: 🐞 Fix

#166 [#164] Fix: 지하철 피커 적용
  src/apis/userProfileEdit.ts
  src/assets/icon-sprite.svg
  src/components/Drawer/index.tsx
  src/components/Icon/type.ts
  src/components/OptionFilterBar/OptionSubwaySelect.tsx
  src/components/OptionFilterBar/index.tsx
  src/components/SubwaySelect/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/formSchema.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/gatheringCreateRequestMapper.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringList/index.tsx
  src/pages/ProfileEdit/components/ProfileEditForm/formSchema.ts
  src/pages/ProfileEdit/components/ProfileEditForm/index.tsx
  src/pages/ProfileEdit/components/ProfileEditForm/profileEditMapper.ts
  src/pages/ProfileEdit/components/ProfileEditForm/useProfileEdit.ts
  src/pages/Register/components/RegisterForm/formSchema.ts
  src/pages/Register/components/RegisterForm/index.tsx
  src/pages/Register/components/RegisterForm/registerMapper.ts
  src/utils/extractFromSubwayName.ts
Labels: 🐞 Fix

#173 [#172] Fix: 트랜지션, 다크모드, 공통 오류 핸들링 관련 버그 수정
  src/components/GatheringList/index.tsx
  src/components/LocationSelect/LocationListModal.tsx
  src/components/Modal/index.tsx
  src/components/SubwaySelect/SubwayLineList.tsx
  src/components/SubwaySelect/SubwayListModal.tsx
  src/components/SubwaySelect/SubwayStationList.tsx
  src/components/UserProfile/UserSignalTemperature.tsx
  src/pages/BoardGameDetail/index.tsx
  src/pages/BoardGameList/index.tsx
  src/pages/ChatRoom/components/ChatContainer/index.tsx
  src/pages/ChatRoomList/components/ChatRoomList/index.tsx
  src/pages/EndGames/components/EndGameList/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringDetail/components/GatheringIntroduce/index.tsx
  src/pages/GatheringDetail/components/GatheringParticipants/index.tsx
  src/pages/GatheringFix/index.tsx
  src/pages/GatheringList/components/GatheringList/index.tsx
  src/pages/GatheringUnfix/hooks/useBlockIfNotFixed.ts
  src/pages/GatheringUnfix/hooks/useBlockNonParticipant.ts
  src/pages/GatheringUnfix/index.tsx
  src/pages/NotificationList/index.tsx
  src/pages/Profile/components/SignalTemperature/index.tsx
  src/pages/Profile/index.tsx
  src/pages/ProfileEdit/components/ProfileEditForm/index.tsx
  src/pages/Register/components/RegisterForm/index.tsx
  src/pages/ReviewCreate/components/ReviewForm/index.tsx
Labels: 🐞 Fix

#168 [#165] Fix: 모임상세페이지 수정
  src/Router.tsx
  src/apis/gatheringDetail.ts
  src/apis/loggedInUser.ts
  src/components/GatheringListItem/index.tsx
  src/components/UserProfile/index.tsx
  src/pages/GatheringDetail/components/GatheringButton/index.tsx
  src/pages/GatheringDetail/components/GatheringIntroduce/index.tsx
  src/pages/GatheringDetail/components/GatheringParticipants/index.tsx
  src/pages/GatheringDetail/components/TabMenu/index.tsx
  src/pages/GatheringDetail/index.tsx
  src/pages/GatheringFix/index.tsx
  src/pages/GatheringUnfix/index.tsx
Labels: 🔨 Refactor

#179 [#178] Fix: 보드게임 목록 조회 필터링 조건 버그 수정
  src/apis/boardGameList.ts
Labels: 🐞 Fix

#181 [#180] Fix: Toast 라이트테마 텍스트 색상, 옵션필터바 key
  src/components/OptionFilterBar/index.tsx
  src/utils/showToast.tsx
Labels: 🐞 Fix

#176 [#167] Fix: 채팅방 페이지 버그 수정 및 안내 메시지 추가
  src/apis/chatRoomMessages.ts
  src/apis/gatheringList.ts
  src/apis/kickParticipant.ts
  src/components/Alert/index.tsx
  src/components/ReverseInfiniteScrollAutoFetch/index.tsx
  src/constants/messages/alert.ts
  src/constants/messages/emptyScreens.ts
  src/hooks/useSendChatMessage.ts
  src/pages/BoardGameDetail/components/BoardGameTipList/index.tsx
  src/pages/ChatRoom/components/ChatContainer/ChatAlert.tsx
  src/pages/ChatRoom/components/ChatContainer/ChatBubble.tsx
  src/pages/ChatRoom/components/ChatContainer/index.tsx
  src/pages/ChatRoom/components/ChatInput/index.tsx
  src/pages/ChatRoom/components/ChatTextarea/index.tsx
  src/pages/ChatRoom/index.tsx
  src/pages/ChatRoomList/components/ChatRoomList/ChatRoomListItem.tsx
  src/pages/ChatRoomList/components/ChatRoomList/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringDetail/components/GatheringButton/index.tsx
  src/pages/GatheringDetail/hooks/useGatheringEntrance.ts
  src/pages/GatheringDetail/hooks/useGatheringLeave.ts
  src/pages/GatheringDetail/hooks/useKickParticipant.ts
  src/pages/GatheringFix/GatheringFixForm/index.tsx
  src/pages/GatheringFix/GatheringFixForm/useGatheringFix.ts
  src/pages/GatheringUnfix/hooks/useGatheringUnfix.ts
  src/pages/GatheringUnfix/index.tsx
  src/stories/components/Alert.stories.tsx
  src/stories/pages/ChatRoom/ChatBubble.stories.tsx
  src/utils/time.ts
Labels: 🐞 Fix

#170 [#169] Fix: 보드게임 상세페이지 , 모임확정 페이지
  src/Router.tsx
  src/apis/postGatheringFix.ts
  src/constants/messages/alert.ts
  src/pages/BoardGameDetail/components/BoardGameTipList/MyTipItem.tsx
  src/pages/BoardGameDetail/components/BoardGameTipList/index.tsx
  src/pages/BoardGameDetail/hooks/useBoardGameTipLike.ts
  src/pages/BoardGameDetail/hooks/useBoardGameWish.ts
  src/pages/GatheringDetail/components/GatheringButton/index.tsx
  src/pages/GatheringDetail/components/GatheringGuide/index.tsx
  src/pages/GatheringFix/GatheringFixForm/gatheringFixRequestMapper.ts
  src/pages/GatheringFix/GatheringFixForm/index.tsx
  src/pages/GatheringFix/GatheringFixForm/useGatheringFix.ts
  src/utils/time.ts
Labels: 🐞 Fix, 🔨 Refactor

#174 [#171] Fix : 프로필수정 , 회원가입 페이지, FCM , Tooltip 수정
  public/firebase-messaging-sw.js
  public/logo.png
  src/components/GatheringList/GatheringListItem.tsx
  src/components/Modal/index.tsx
  src/components/TextInput/index.tsx
  src/constants/messages/error.ts
  src/hooks/useInitializeFCM.ts
  src/index.css
  src/main.tsx
  src/pages/GatheringCreate/index.tsx
  src/pages/Profile/components/SignalTemperature/index.tsx
  src/pages/Profile/index.tsx
  src/pages/ProfileEdit/components/ProfileEditForm/formSchema.ts
  src/pages/ProfileEdit/components/ProfileEditForm/index.tsx
  src/pages/Register/components/RegisterForm/index.tsx
  src/pages/Register/index.tsx
  src/utils/activateColorTheme.ts
Labels: 🐞 Fix, 🔨 Refactor

#183 [#182]Fix : 모임상세페이지 수정
  src/pages/GatheringDetail/components/GatheringIntroduce/index.tsx
  src/pages/GatheringDetail/components/TabMenu/index.tsx
Labels: 🐞 Fix

#187 [#175] Fix: FCM 호출 코드 header에 AccessToken 포함
  src/hooks/useInitializeFCM.ts
Labels: 🐞 Fix

#184 [#177] Fix: 종료된 게임 페이지 버그 수정
  src/apis/endGameList.ts
  src/apis/endGameUser.ts
  src/apis/loggedInUser.ts
  src/assets/logo.png
  src/assets/smiling-face.png
  src/assets/tab-bar-logo.png
  src/components/Drawer/index.tsx
  src/components/EndGameListItem/index.tsx
  src/components/GatheringList/GatheringListItem.tsx
  src/components/GatheringListItem/index.tsx
  src/components/LocationSelect/LocationListModal.tsx
  src/components/LocationSelect/index.tsx
  src/components/OptionFilterBar/OptionSubwaySelect.tsx
  src/components/SubwaySelect/SubwayListModal.tsx
  src/components/SubwaySelect/index.tsx
  src/components/UserProfile/index.tsx
  src/constants/messages/emptyScreens.ts
  src/hooks/useAutoCloseModal.ts
  src/pages/BoardGameDetail/components/BoardGameTipList/MyTipItem.tsx
  src/pages/BoardGameDetail/components/BoardGameTipList/TipItem.tsx
  src/pages/BoardGameList/components/BoardGameList/BoardGameListItem.tsx
  src/pages/ChatRoom/components/ChatContainer/ChatBubble.tsx
  src/pages/ChatRoom/components/ChatTextarea/index.tsx
  src/pages/EndGames/components/EndGameList/index.tsx
  src/pages/EndGames/index.tsx
  src/pages/GatheringCreate/components/GatheringCreateForm/formSchema.ts
  src/pages/GatheringCreate/components/GatheringCreateForm/index.tsx
  src/pages/GatheringDetail/components/GatheringIntroduce/index.tsx
  src/pages/GatheringList/components/GatheringList/index.tsx
  src/pages/NotificationList/components/NotificationList/NotificationListItem.tsx
  src/pages/Profile/components/PersonalInfo/index.tsx
  src/pages/ReviewCreate/index.tsx
  src/stories/pages/ReviewCreate/index.stories.tsx
Labels: 🐞 Fix

#189 [#188] Fix: 뒤로가기 제어
  src/components/UserProfile/index.tsx
  src/pages/CreateBoardGameTip/index.tsx
  src/pages/GatheringCreate/index.tsx
  src/pages/GatheringDetail/components/GatheringButton/index.tsx
  src/pages/GatheringDetail/components/TabMenu/index.tsx
  src/pages/GatheringDetail/index.tsx
  src/pages/GatheringFix/index.tsx
  src/pages/GatheringUnfix/index.tsx
  src/pages/Profile/hooks/useLogout.ts
  src/pages/ProfileEdit/index.tsx
  src/pages/Register/index.tsx
  src/pages/ReviewCreate/index.tsx
Labels: 🐞 Fix
