Repository BoardSignal/Team-CivilWar-BoardSignal-FE, pull requests merged in 2024-02, with the labels that each got.

#2 [#1] Feat: PC에서도 모바일 레이아웃으로 표시하게
  .gitignore
  .prettierrc
  src/Router.tsx
  src/assets/logo.png
  src/components/layout/Introduction.tsx
  src/components/layout/index.tsx
Labels: ✨ Feature

#5 [#4] Chore: Prettier ESLint 세팅
  .eslintrc.cjs
  .prettierrc
  commitlint.config.cjs
  package.json
  pnpm-lock.yaml
  src/App.tsx
Labels: ⚙ Chore

#13 [#12] Chore: Storybook, msw 초기 설정
  .github/workflows/publish-storybook.yaml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/App.tsx
  src/ReactQueryClientProvider.tsx
  src/stories/HomePage.stories.tsx
Labels: ⚙ Chore

#16 [#15] Style: Tailwind에 Figma 상의 color config 추가
  src/index.css
  tailwind.config.js
Labels: 🎨 Style

#18 [#14] Feat: 공통컴포넌트 - Icon
  src/assets/icon-sprite.svg
  src/components/Icon/index.tsx
  src/components/Icon/type.ts
  src/stories/components/Icon.stories.tsx
Labels: ✨ Feature

#6 [#3] Feat: 공통컴포넌트 - GNB
  src/Router.tsx
  src/assets/icon-sprite.svg
  src/components/Icon/type.ts
  src/components/gnb/index.tsx
  src/components/gnb/routes.ts
  src/components/layout/index.tsx
  src/pages/HomePage.tsx
  src/stories/components/GNB.stories.tsx
Labels: ✨ Feature

#21 [#19] Feat: 공통컴포넌트 Input 구현
  src/components/TextInput/index.tsx
  src/stories/components/TextInput.stories.tsx
Labels: ✨ Feature

#33 [#32] Fix: Button의 Ripple의 사용 방식 변경 및 ghost variant 추가
  src/components/Button/index.tsx
  src/components/GNB/index.tsx
  src/components/Ripple/index.tsx
  src/stories/components/Button.stories.tsx
Labels: 🐞 Fix

#26 [#25] Feat: 공통컴포넌트 상단 탭 바
  src/assets/icon-sprite.svg
  src/components/Icon/type.ts
  src/components/TabBar/index.tsx
  src/stories/components/TabBar.stories.tsx
Labels: ✨ Feature

#28 [#27] Feat: 공통컴포넌트 - Drawer
  .storybook/preview.tsx
  src/components/Drawer/DrawerContent.tsx
  src/components/Drawer/DrawerTitle.tsx
  src/components/Drawer/DrawerTrigger.tsx
  src/components/Drawer/index.tsx
  src/index.css
  src/stories/components/Drawer.stories.tsx
  src/stories/components/Icon.stories.tsx
  tailwind.config.js
Labels: ✨ Feature

#17 [#8] Feat: 카카오 로그인버튼 구현
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/Router.tsx
  src/apis/core.ts
  src/apis/kakaoLogin.ts
  src/apis/naverLogin.ts
  src/assets/kakao-login-button.png
  src/main.tsx
  src/pages/Login/hooks/useKakaoLogin.ts
  src/pages/Login/hooks/useNaverLogin.ts
  src/pages/Login/index.tsx
Labels: ✨ Feature

#34 [#31] Feat: 공통컴포넌트 - MultipleSelect
  src/components/MultipleSelect/OptionItemButton.tsx
  src/components/MultipleSelect/index.tsx
  src/stories/components/MultipleSelect.stories.tsx
Labels: ✨ Feature

#51 [#48] Refactor: Storybook의 기본 스토리 Decorator 설정 및 권장 문서화
  .storybook/preview.tsx
  src/Router.tsx
  src/components/Drawer/index.tsx
  src/components/Layout/Introduction.tsx
  src/components/Layout/LayoutRootPortal.tsx
  src/components/Layout/index.tsx
  src/stories/CommonPageLayoutDecorator.tsx
  src/stories/components/Button.stories.tsx
  src/stories/components/Drawer.stories.tsx
  src/stories/components/TabBar.stories.tsx
  src/stories/pages/HomePage.stories.tsx
Labels: 🔨 Refactor

#49 Feat: 프로필페이지 시그널 온도 구현
  package.json
  pnpm-lock.yaml
  src/assets/smiling-face.png
  src/components/Popover/index.tsx
  src/index.css
  src/pages/profile/components/SignalTemperature/index.tsx
  src/stories/pages/profile/Temperature.stories.tsx
  tailwind.config.js
Labels: ✨ Feature

#52 Feat: 프로필페이지 사용자 프로필 구현
  src/pages/profile/components/PersonalInfo/index.tsx
  src/stories/pages/profile/Profile.stories.tsx
Labels: ✨ Feature

#46 [#43] Feat: 공통컴포넌트 - ImageUpload
  src/components/ImageUpload/ImageUploadButton.tsx
  src/components/ImageUpload/index.tsx
  src/stories/components/ImageUpload.stories.tsx
Labels: ✨ Feature

#42 [#39] Feat: 공통컴포넌트 - Checkbox
  src/components/Checkbox/index.tsx
  src/stories/components/Checkbox.stories.tsx
Labels: ✨ Feature

#55 [#53]Feat: 프로필페이지 Review컴포넌트 구현
  src/pages/profile/components/MannerReview/index.tsx
  src/stories/pages/profile/Review.stories.tsx
Labels: ✨ Feature

#57 [#56] Style: 로그인 페이지 추가 퍼블리싱
  src/Router.tsx
  src/components/TabBar/index.tsx
  src/pages/Login/components/LoginButtons.tsx
  src/pages/Login/index.tsx
  src/stories/pages/LoginPage.stories.tsx
Labels: 🎨 Style

#64 [#40] Feat: 공통컴포넌트 - Range
  src/components/Range/index.tsx
  src/index.css
  src/stories/components/Range.stories.tsx
Labels: ✨ Feature

#61 [#60]Feat: 보드게임 상세페이지 - 보드게임 정보
  src/Router.tsx
  src/pages/BoardGameDetail/components/GameDescription/index.tsx
  src/pages/BoardGameDetail/components/GamePlayDetail/index.tsx
  src/pages/BoardGameDetail/components/GameSummary/index.tsx
  src/pages/BoardGameDetail/components/GameWish/index.tsx
  src/pages/BoardGameDetail/index.tsx
  src/pages/Profile/components/PersonalInfo/index.tsx
  src/pages/Profile/components/SignalTemperature/index.tsx
  src/stories/pages/BoardGameDetail/GameDescription.stories.tsx
  src/stories/pages/BoardGameDetail/GamePlayDetail.stories.tsx
  src/stories/pages/BoardGameDetail/GameSummary.stories.tsx
  src/stories/pages/BoardGameDetail/GameWish.stories.tsx
  src/stories/pages/BoardGameDetail/index.stories.tsx
  src/stories/pages/Profile/Profile.stories.tsx
  src/stories/pages/Profile/Temperature.stories.tsx
Labels: ✨ Feature

#65 [#30]Feat: 내 프로필 페이지
  src/Router.tsx
  src/apis/userProfile.ts
  src/assets/icon-sprite.svg
  src/components/Icon/type.ts
  src/components/TabBar/index.tsx
  src/pages/MyProfile/components/MannerReview/index.tsx
  src/pages/MyProfile/components/PersonalInfo/index.tsx
  src/pages/MyProfile/components/PreferCategory/index.tsx
  src/pages/MyProfile/components/SignalTemperature/index.tsx
  src/pages/MyProfile/index.tsx
  src/stories/pages/MyProfile/PersonalInfo.stories.tsx
  src/stories/pages/MyProfile/Review.stories.tsx
  src/stories/pages/MyProfile/Temperature.stories.tsx
  src/stories/pages/MyProfile/index.stories.tsx
  src/stories/pages/profile/Review.stories.tsx
Labels: ✨ Feature

#74 [#73] Refactor: 공통컴포넌트 - Textarea
  src/components/TextArea/index.tsx
  src/stories/components/Label.stories.tsx
  src/stories/components/TextArea.stories.tsx
Labels: 🔨 Refactor

#58 [#54] Feat: 공통컴포넌트 - Modal
  src/components/Modal/index.tsx
  src/stories/components/Modal.stories.tsx
Labels: ✨ Feature
