Repository BoardSignal/Team-CivilWar-BoardSignal-FE, pull requests merged in 2024-04, with the labels that each got.

#192 [#191] Fix: 스타일 및 버그 수정
  src/components/EndGameListItem/index.tsx
  src/components/Modal/index.tsx
  src/components/Select/index.tsx
  src/pages/BoardGameDetail/index.tsx
  src/pages/BoardGameWishList/index.tsx
  src/pages/EndGames/index.tsx
  src/pages/GatheringDetail/components/GatheringButton/index.tsx
  src/pages/GatheringDetail/components/GatheringDescription/index.tsx
  src/pages/GatheringList/components/GatheringList/index.tsx
  src/pages/GatheringList/index.tsx
  src/pages/NotificationList/components/NotificationList/NotificationListItem.tsx
  src/pages/ReviewCreate/index.tsx
Labels: 🐞 Fix

#198 [#197] Feat: 모임, 보드게임 검색 기능 추가
  src/apis/gatheringList.ts
  src/components/OptionFilterBar/index.tsx
  src/components/SearchBar/index.tsx
  src/components/TabBar/index.tsx
  src/constants/messages/placeholder.ts
  src/mocks/gatheringList.ts
  src/pages/BoardGameList/components/BoardGameListOptionFilterBar/index.tsx
  src/pages/BoardGameList/index.tsx
  src/pages/GatheringList/components/GatheringList/index.tsx
  src/pages/GatheringList/components/GatheringListOptionFilterBar/index.tsx
  src/pages/GatheringList/hooks/useGatheringListQueryParams.ts
  src/pages/GatheringList/index.tsx
  src/stories/components/OptionFilterBar.stories.tsx
  src/stories/components/SearchBar.stories.tsx
  src/stories/pages/GatheringListPage.stories.tsx
Labels: ✨ Feature

#205 [#204] Docs: README
  README.md
Labels: 📃 Docs
